// Income  Statement router

// Applications :
// (i) to create income statement pdf --- TOCHANGE

// Requirements
const express = require("express");
const cors = require("cors");
const bodyparser = require("body-parser");
const htmlpdf = require("html-pdf");

// IncomeStatementRouter           ---- TOCHANGE
const insRouter = express.Router();

// Templates
const pdfTemplate = require("../views/template/ins"); // --TOCHANGE

// Per file Variables
var file_count = 0;
const gen_file_name = "income_sheet"; // --TOCHANGE

// Middleware
insRouter.use(cors());
insRouter.use(bodyparser.urlencoded({ extended: true }));
insRouter.use(bodyparser.json());

// POST - to make server to genarate pdf
// GET - after making post request - again we need to ask the server to give the pdf generated by it

// Creates pdf
// notifies frontend that he created the pdf
insRouter.post("/create", (req, res) => {
  //console.log(`${req.body.name}`);
  console.log("Post Request to generate file -> From Backend");
  htmlpdf
    .create(pdfTemplate(req.body), {})
    .toFile(`${gen_file_name}_${file_count}.pdf`, (err) => {
      if (err) {
        Promise.reject();
      }
      res.send(Promise.resolve());
    });
});

// He gives the pdf which is created by the createpdf
insRouter.get("/get", (_req, res) => {
  const dirpath = __dirname;
  console.log("Post Request to display file -> From Backend");
  var path = "",
    lastIndex = 0;
  for (var i = 0; i < dirpath.length; i++) {
    if (dirpath[i] == "\\") {
      lastIndex = i;
    }
  }
  path = dirpath.substring(0, lastIndex);
  res.sendFile(`${__dirname}/${gen_file_name}_${file_count}.pdf`);
  file_count++;
  console.log("Post Request to display file -> From Backend Complete");
});

module.exports = insRouter;
