// Letter of credit router

// Applications :
// (i) to create loc pdf

// Requirements
const express = require("express");
const cors = require("cors");
const bodyparser = require("body-parser");
const htmlpdf = require("html-pdf");

// LocRouter
const locRouter = express.Router();

// Templates
const pdfTemplate = require("../views/template/loc");

// Per file Variables
var file_count = 0;
const gen_file_name = "letter_of_credit";

// Middleware
locRouter.use(cors());
locRouter.use(bodyparser.urlencoded({ extended: true }));
locRouter.use(bodyparser.json());

// POST - to make server to genarate pdf
// GET - after making post request - again we need to ask the server to give the pdf generated by it

// Creates pdf
// notifies frontend that he created the pdf
locRouter.post("/createpdf", (req, res) => {
	//console.log(`${req.body.name}`);
	htmlpdf
		.create(pdfTemplate(req.body), {})
		.toFile(`${gen_file_name}_${file_count}.pdf`, (err) => {
			if (err) {
				Promise.reject();
			}
			res.send(Promise.resolve());
		});
});

// He gives the pdf which is created by the createpdf
locRouter.get("/getpdf", (_req, res) => {
	res.sendFile(`${__dirname}/${gen_file_name}_${file_count}.pdf`);
	file_count++;
});

module.exports = locRouter;
